Map/Controllers/GateController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Map.Controllers
{
    public class GateController:Controller
    {
        GateManager gateManager = new GateManager(new EfGateDal());
        NeighborhoodManager neighborhoodManager = new NeighborhoodManager(new EfNeighborhoodDal());
        [HttpGet]
        public ActionResult GateAdd()
        {
            List<SelectListItem> valueNeighborhood = (from x in neighborhoodManager.GetList()
                                                      select new SelectListItem
                                                      {
                                                          Text = x.NeighborhoodName,
                                                          Value = x.NeighborhoodId.ToString()
                                                      }).ToList();
            ViewBag.vnn = valueNeighborhood;

            return View();
        }
        [HttpPost]
        public ActionResult GateAdd(Gate gate)
        {
            GateValidator gateValidator = new GateValidator();
            ValidationResult results = gateValidator.Validate(gate);
            if (results.IsValid)
            {

                gateManager.GateAdd(gate);
                return RedirectToAction("Index", "Map");
            }
            else
            {
                foreach(var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult GateGetList()
        {
            var gateValues = gateManager.GetList();
            return View(gateValues);
        }
        [HttpGet]
        public ActionResult GateEdit(int id)
        {
            List<SelectListItem> valueNeighborhood = (from x in neighborhoodManager.GetList()
                                                      select new SelectListItem
                                                      {
                                                          Text = x.NeighborhoodName,
                                                          Value = x.NeighborhoodId.ToString()
                                                      }).ToList();
            ViewBag.vnn = valueNeighborhood;
            var gateValue = gateManager.GateGetById(id);
            return View(gateValue);
        }
        [HttpPost]
        public ActionResult GateEdit(Gate gate)
        {   
                gateManager.GateUpdate(gate);
                return RedirectToAction("GateGetList");
        }
        public ActionResult GateDelete(int id)
        {
            var deleteValue = gateManager.GateGetById(id);
            gateManager.GateDelete(deleteValue);
            return RedirectToAction("GateGetList");
        }
    }
}

Map/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Map.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Map/Controllers/MapController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Map.Controllers
{
    public class MapController : Controller
    {
        NeighborhoodManager neighborhoodManager = new NeighborhoodManager(new EfNeighborhoodDal());
        // GET: Map
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Polygon(int id)
        {
            var cordinateid = neighborhoodManager.NeighborhoodGetById(id);
            ViewBag.nn = cordinateid.NeighborhoodName;
            ViewBag.ci = cordinateid.NeighborhoodCoordinate;
            return View();

        }
       
    }
}

Map/Controllers/NeighborhoodController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Map.Controllers
{
    public class NeighborhoodController : Controller
    {
        NeighborhoodManager neighborhoodManager = new NeighborhoodManager(new EfNeighborhoodDal());
        [HttpGet]
        public ActionResult NeighborhoodAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NeighborhoodAdd(Neighborhood neighborhood)
        {
            NeighborhoodValidator neighborhoodValidator = new NeighborhoodValidator();
            ValidationResult results = neighborhoodValidator.Validate(neighborhood);
            if (results.IsValid)
            {
                neighborhoodManager.NeighborhoodAdd(neighborhood);
                return RedirectToAction("Index", "Map");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult NeighborhoodGetList()
        {
            var neighborhoodValues = neighborhoodManager.GetList();
            return View(neighborhoodValues);
        }
        [HttpGet]
        public ActionResult NeighborhoodEdit(int id)
        {
            var neighborhoodValue = neighborhoodManager.NeighborhoodGetById(id);
         
            return View(neighborhoodValue);
        }
        [HttpPost]
        public ActionResult NeighborhoodEdit(Neighborhood neighborhood)
        {
            neighborhoodManager.NeighborhoodUpdate(neighborhood);
            return RedirectToAction("NeighborhoodGetList");
        }
        public ActionResult NeighborhoodDelete(int id)
        {
            var deleteValue = neighborhoodManager.NeighborhoodGetById(id);
            neighborhoodManager.NeighborhoodDelete(deleteValue);
            return RedirectToAction("NeighborhoodGetList");
        }
    }
}

Map/Views/Gate/GateAdd.cshtml
@model EntityLayer.Concrete.Gate
@{
    ViewBag.Title = "GateAdd";
    Layout = "~/Views/Shared/View1.cshtml";
}

<h2>Yeni Mahalle Ekleme Sayfası</h2>
<br />
@using (Html.BeginForm("GateAdd", "Gate", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kapı Numarasını Girin ")
        @Html.TextBoxFor(x => x.GateNo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.GateNo)
        <br /><br />
        @Html.Label("Mahalle:")
        @Html.DropDownListFor(x => x.NeighborhoodId, (List<SelectListItem>)ViewBag.vnn, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Kapı Koordinat Noktalarını Girin:")
        @Html.TextBoxFor(x => x.GateCoordinate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.GateCoordinate)
        <br /><br />
        <button class="btn btn-info">Ekle</button>
    </div>
}

Map/Views/Gate/GateEdit.cshtml
@model EntityLayer.Concrete.Gate
@{
    ViewBag.Title = "GateEdit";
    Layout = "~/Views/Shared/View1.cshtml";
}
@using (Html.BeginForm("GateEdit", "Gate", FormMethod.Post))
{
    <h2>Kapı Güncelleme Sayfası</h2>
    <div class="form-group">
        @Html.Label("Kapı Numarasını Girin ")
        @Html.TextBoxFor(x => x.GateNo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.GateNo)
        <br /><br />
        @Html.Label("Mahalle:")
        @Html.DropDownListFor(x => x.NeighborhoodId, (List<SelectListItem>)ViewBag.vnn, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Kapı Koordinat Noktalarını Girin:")
        @Html.TextBoxFor(x => x.GateCoordinate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.GateCoordinate)
        <br /><br />
        <button class="btn btn-info">Güncelle</button>
    </div>
}

Map/Views/Gate/GateGetList.cshtml
@using EntityLayer.Concrete
@model List<Gate>

@{
    ViewBag.Title = "GateGetList";
    Layout = "~/Views/Shared/View1.cshtml";
}
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kapı No</th>
        <th>Mahalle İsmi</th>
        <th>Koordinat Noktası</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.GateId</th> @*th kalın yapar ifadeyi*@
            <td>@item.GateNo</td>
            <td>@item.GateCoordinate</td>
            <td>@item.Neighborhood.NeighborhoodName</td>
            <td><a href="/Gate/GateDelete/@item.GateId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Gate/GateEdit/@item.GateId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Map/Index" class="btn btn-primary">Haritalar</a></td>
        </tr>
    }

</table>
<br />

Map/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Map/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Map/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Map/Views/Map/Index.cshtml
@using EntityLayer.Concrete
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/View1.cshtml";
}
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css" type="text/css">
    <style>
        .map {
            height: 750px;
            width: 100%;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js"></script>
    <title>OpenLayers example</title>
</head>
<body>
    <h2>Harita</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
            center: ol.proj.fromLonLat([36.42, 39.45]),
            zoom: 6.7
        })
      });
    </script>
</body>
</html>
<a href="/Neighborhood/NeighborhoodAdd" class="btn btn-info">Mahalle Ekle</a>
<a href="/Gate/GateAdd" class="btn btn-info">Kapı Ekle</a>

Map/Views/Map/Polygon.cshtml
@{
    ViewBag.Title = "Polygon";
    Layout = "~/Views/Shared/View1.cshtml";
}
@{ 
    string sayac =ViewBag.ci;
}
<h2>Rabia</h2>
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css" type="text/css">
    <style>
        .map {
            height: 750px;
            width: 100%;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js"></script>
    <title>OpenLayers example</title>
</head>
<body>
    <h2>Harita</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
       var raster = new ol.layer.Tile({
        source: new ol.source.OSM()
      });

      var wkt = 'POLYGON((10.689 -25.092, 34.595 ' +
          '-20.170, 38.814 -35.639, 13.502 ' +
          '-39.155, 10.689 -25.092))';

      var format = new ol.format.WKT();

      var feature = format.readFeature(wkt, {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857'
      });

      feature.set('MahalleAdi','Deneme Mahalle');
       feature.set('MahalleId',1);

      var vector = new ol.layer.Vector({
        source: new ol.source.Vector({
          features: [feature]
        })
      });

       var vectorBilgiAl = new ol.layer.Vector({
        title:'Bilgi Al',
        source: new ol.source.Vector({}),
        wrapX: false
      });

      var map = new ol.Map({
        layers: [raster, vector,vectorBilgiAl],
        target: 'map',
        view: new ol.View({
            center: [@sayac],
            zoom: 4
        })
      });

       var  bilgiAl= new ol.interaction.Draw({
            source: vectorBilgiAl.getSource(),
            type: ('Point')
        });

      map.addInteraction(bilgiAl);

      bilgiAl.on('drawend', function (event) {
                var tiklanilanNoktaVerileri=[];

                var format = new ol.format.WKT();

                var selFeatureWkt = format.writeGeometry(event.feature.getGeometry(), {
                    dataProjection: 'EPSG:3857',
                    featureProjection: 'EPSG:3857'
                });
                //alert(selFeatureWkt);

                vector.getSource().getFeatures().forEach(function(obje){

                var objeExtend=obje.getGeometry().getExtent();

                    var sonuc=ol.extent.intersects(objeExtend,event.feature.getGeometry().getExtent());
                    if(sonuc){
                        tiklanilanNoktaVerileri.push(obje.get('MahalleAdi')+'#'+obje.get('MahalleId'))
                        }
                    }
                );

                if(tiklanilanNoktaVerileri.length>0){

                    alert('Tıklanılan Nokta Verileri : '+tiklanilanNoktaVerileri);
                }
                else
                {
                    alert('Tıklanılan noktada mahalle verisi bulunamadı !');
                }

                vectorBilgiAl.getSource().clear();

            });

        var select = new ol.interaction.Select({
                    wrapX: false
                    });
        var modify = new ol.interaction.Modify({
                    features: select.getFeatures()
                    });
        map.addInteraction(select);
        map.addInteraction(modify);
        //select.setActivate(false);
        //modify.setActivate(false);

        modify.on('modifyend',function(e){
                    alert('Düzenleme Bitti');
                    //console.log("feature id is",e.features.getArray()[0].getId());
                    });
        modify.on('change:active',function(e){
                    alert('change:active');
                    //console.log("feature id is",e.features.getArray()[0].getId());
                    });
        modify.on('propertychange',function(e){
                    alert('Propery Change');
                    //console.log("feature id is",e.features.getArray()[0].getId());
                    });
        bilgiAl.setActive(false);
        select.setActive(true);
    </script>
</body>
</html>

Map/Views/Neighborhood/NeighborhoodAdd.cshtml
@model EntityLayer.Concrete.Neighborhood
@{
    ViewBag.Title = "NeighborhoodAdd";
    Layout = "~/Views/Shared/View1.cshtml";
}

<h2>Yeni Mahalle Ekleme Sayfası</h2>
<br/>
@using (Html.BeginForm("NeighborhoodAdd", "Neighborhood", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Mahalle İsmini Giriniz")
    @Html.TextBoxFor(x => x.NeighborhoodName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.NeighborhoodName)
    <br /><br />
    @Html.Label("Koordinat Noktalarını Girin:")
    @Html.TextBoxFor(x => x.NeighborhoodCoordinate, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.NeighborhoodCoordinate)
    <br /><br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

Map/Views/Neighborhood/NeighborhoodEdit.cshtml
@model EntityLayer.Concrete.Neighborhood
@{
    ViewBag.Title = "NeighborhoodEdit";
    Layout = "~/Views/Shared/View1.cshtml";
}
<br />
<h2>Mahalle Güncelleme Sayfası</h2>
@using (Html.BeginForm("NeighborhoodEdit", "Neighborhood", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Mahalle ID")
        @Html.TextBoxFor(x => x.NeighborhoodId, new { @class = "form-control" })
        <br />
        @Html.Label("Mahalle Adı")
        @Html.TextBoxFor(x => x.NeighborhoodName, new { @class = "form-control" })   
        <br />
        @Html.Label("Koordinat Noktaları")
        @Html.TextAreaFor(x => x.NeighborhoodCoordinate, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

Map/Views/Neighborhood/NeighborhoodGetList.cshtml
@using EntityLayer.Concrete
@model List<Neighborhood>
@{
    ViewBag.Title = "NeighborhoodGetList";
    Layout = "~/Views/Shared/View1.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Mahalle Adı</th>
        <th>Koordinat</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.NeighborhoodId</th> @*th kalın yapar ifadeyi*@
            <td>@item.NeighborhoodName</td>
            <td>@item.NeighborhoodCoordinate</td>
            <td><a href="/Neighborhood/NeighborhoodDelete/@item.NeighborhoodId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Neighborhood/NeighborhoodEdit/@item.NeighborhoodId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Map/Polygon/@item.NeighborhoodId" class="btn btn-primary">Haritalar</a></td>
        </tr>
    }

</table>
<br />

Map/Views/Shared/View.cshtml
@{
    ViewBag.Title = "View";
}

<h2>View</h2>

Map/Views/Shared/View1.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Dashboard 3</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/İMAGE/amblem-ana.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">BAŞARSOFT</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">                    
                        <img src="~/İMAGE/rabia.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Rabia Nur Kavi</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                       
                            <li class="nav-item has-treeview ">
                                <a href="/Map/Index/" class="nav-link ">
                                    <i class="nav-icon fas fa-map-marker-alt"></i>
                                    <p>
                                        Harita

                                    </p>
                                </a>

                            </li>
                        <li class="nav-item has-treeview">
                            <a href="/Gate/GateGetList" class="nav-link">
                                <i class="nav-icon fas fa-door-closed"></i>
                                <p>
                                    Kapı Düzenleme

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="/Neighborhood/NeighborhoodGetList/" class="nav-link">
                                <i class="nav-icon fas fa-city"></i>
                                <p>
                                    Mahalle Düzenleme 
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Gallery/Index/" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>                   
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Çıkış Yap

                                </p>
                            </a>

                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->


    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    @*<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>